<?php
namespace backend\controllers;

use backend\service\UserService;
use common\models\AdminModel;
use common\tools\Tool_Common;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class BaseController extends Controller
{
    public $_post;
    public $_get;
    public $_account;
    public $_user_id;
    public $service;
    public $user_type;

    /**
     * 参数存放
     * @var array
     */
    public static $params = [];

    public function init()
    {
        parent::init();
        $this->_user_id = Yii::$app->user->id;
        //if(in_array($this->_post['user_id'], [1,2])){ } # 用户限制
        self::_initData();
        $this->_post = \Yii::$app->request->post();
        $this->_get = \Yii::$app->request->get();
    }

    public function _initData(){
        if (Yii::$app->user->isGuest || empty($this->_user_id)) {
            return;
        }

        $User = AdminModel::findOne($this->_user_id);
        if (empty($User)) {
            Yii::$app->user->logout();
            return;
        }

        $userLoginAccessTokenDatas = UserService::getUserLoginInfo($this->_user_id);
        $session_id = Yii::$app->getSession()->id;
        $this->user_type = $User->user_type;
        if(in_array($this->_user_id, \Yii::$app->params['SINGLE_LOGIN_UIDS']) && !empty($userLoginAccessTokenDatas)){
            if(!in_array($session_id, $userLoginAccessTokenDatas)){
                Yii::$app->user->logout();
                return $this->goHome();
            }
        }
        Tool_Common::log('/user/'.__FUNCTION__, 'INFO', '用户登陆access_token信息', ['uid'=>$this->_user_id, 'session_id'=>$session_id, 'userLoginAccessTokenDatas'=>$userLoginAccessTokenDatas]);
        $this->_account = $User->username;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

    /**
     * 后端验证方法
     * 使用例子
     * $a_fields = array(
     *     'name'=>array( 'type'=>'string', 'min'=>1, 'max'=>500,'message'=>'名称参数错误' ),//非中文字符串
     *     'email'=>array( 'type'=>'email', 'min'=>1, 'max'=>30,'message'=>'邮箱格式错误' ),//邮箱格式
     *     'mobile'=>array( 'type'=>'mobile', 'min'=>11, 'max'=>11,'message'=>'手机号码格式错误' ),//手机号格式
     *     'note'=>array( 'type'=>'stringUtf8', 'empty'=>true, 'default'=>'', 'max'=>30,'message'=>'邮箱格式错误' ),//支持中文,最多30个字符，允许不传参，默认为空
     *     'title'=>array(
     *          array( 'type'=>'stringUtf8', 'min'=>5, 'message'=>'标题长度不能少于5个字符' ),//支持中文并且最少5个字符限制
     *          array( 'type'=>'stringUtf8', 'max'=>500, 'message'=>'标题长度不能超过500个字符' ),//支持中文并且不能超过500个字符
     *      ),
     *      'type'=>array( 'type'=>'int', 'empty'=>true, 'default'=>0, 'message'=>'类型值参数错误' ),
     *      'status'=>array( 'type'=>'in', 'list'=>array( 'YES',"NO" ), 'message'=>'状态参数错误' ),//枚举参数，只允许在list中出现方可验证通过
     *      'order_id'=>arrat( 'type'=>'id', 'message'=>'订单ID参数错误' )//敏感字段被加密到客户端，返回会自动解密,忽略
     * )；
     * $this->va( $a_feilds, Yii::$app->request->post() );//参数会被存放到self::$params属性中，获取如，$data['name'] =self::$params['name']
     *
     *
     * 更多类型验证请查阅common\tools\UtilValid
     *
     */
    public function va( $aFields, $request = '' )
    {
        $request = empty($request)?( Yii::$app->request->getIsPost()? Yii::$app->request->post():Yii::$app->request->get() ) : $request;
        list($params,$a_error) = \common\tools\UtilValid::va( $request, $aFields );

        if( !empty($a_error) )
        {
            $this->alert( 8888, $a_error['field'].':'.$a_error['message'] );
        }
        static::$params = $params;

    }
}
