<?php
namespace backend\controllers;

use backend\service\UserService;
use common\models\AdminModel;
use common\tools\Tool_Common;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class BaseController extends Controller
{
    public $_post;
    public $_get;
    public $_account;
    public $_user_id;

    public function init()
    {
        parent::init();
        $this->_user_id = Yii::$app->user->id;
        //if(in_array($this->_post['user_id'], [1,2])){ } # 用户限制
        self::_initData();
        $this->_post = \Yii::$app->request->post();
        $this->_get = \Yii::$app->request->get();
    }

    public function _initData(){
        $User = AdminModel::findOne($this->_user_id);
        $userLoginAccessTokenDatas = UserService::getUserLoginInfo($this->_user_id);
        $session_id = Yii::$app->getSession()->id;
        if(in_array($this->_user_id, \Yii::$app->params['SINGLE_LOGIN_UIDS']) && !empty($userLoginAccessTokenDatas)){
            if(!in_array($session_id, $userLoginAccessTokenDatas)){
                Yii::$app->user->logout();
                return $this->goHome();
            }
        }
        Tool_Common::log('/user/'.__FUNCTION__, 'INFO', '用户登陆access_token信息', ['uid'=>$this->_user_id, 'session_id'=>$session_id, 'userLoginAccessTokenDatas'=>$userLoginAccessTokenDatas]);
        $this->_account = $User->username;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

}
