<?php
namespace backend\controllers;

use backend\models\User;
use backend\service\HN0898Service;
use backend\service\UserSysPlansService;
use common\models\AdminModel;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class BaseController extends Controller
{
    public $_post;
    public $_get;
    public $_account;
    public $_user_id;

    public function init()
    {
        parent::init();
        $this->_user_id = Yii::$app->user->id;
        self::_initData();
        $this->_post = \Yii::$app->request->post();
        $this->_get = \Yii::$app->request->get();
    }

    public function _initData(){
        $User = AdminModel::findOne($this->_user_id);
        $this->_account = $User->username;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function render($view, $params = [])
    {
        $lottery_types = UserSysPlansService::getMyLotteryTypes($this->_user_id);
        if(!$queryParams['UserSysPlans']['lottery_type']){
            $lottery_type = $lottery_types[0]['lottery_type'];
        }else{
            $lottery_type = $queryParams['UserSysPlans']['lottery_type'];
        }
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

}
