<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\searchs\StaticCode3nAriseMonth */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Static Code3n Arise Months');
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="static-code3n-arise-month-index wrapper site-min-height">
    <!-- page start-->
    <section class="panel">
        <header class="panel-heading">
            <?= Html::encode($this->title) ?>
            <?php include(dirname(__FILE__).'/index_tab.php'); ?>
        </header>
        <div class="panel-body">
            <div class="adv-table editable-table ">
                <!--div class="clearfix">
                    <div class="btn-group">
                        <?= Html::a(Yii::t('app', 'Create Static Code3n Arise Month'), ['create'], ['class' => 'btn btn-success', 'style' => 'margin-bottom:15px;']) ?>
                    </div>
                </div-->

            <?php //Pjax::begin(); ?>
                <?php include(dirname(__FILE__).'/code_type_tab.php'); ?>
                <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],

                        //'id',
                        'month',
                        'code_137',
                        'code_256',
                        'code_126',
                        'code_238',
                        'code_078',
                        'code_013',
                        'code_589',
                        'code_019',
                        'code_138',
                        'code_014',
                        'code_478',
                        'code_267',
                        'code_125',
                        'code_567',
                        'code_012',
                        'code_139',
                        'code_469',
                        'code_034',
                        'code_018',
                        'code_278',
                        'code_056',
                        'code_569',
                        'code_025',
                        'code_029',
                        'code_356',
                        'code_015',
                        'code_347',
                        'code_348',
                        'code_134',
                        'code_145',
                        //'code_258',
                        //'code_036',
                        //'code_123',
                        //'code_148',
                        //'code_789',
                        //'code_378',
                        //'code_067',
                        //'code_156',
                        //'code_178',
                        //'code_037',
                        //'code_069',
                        //'code_167',
                        //'code_248',
                        //'code_236',
                        //'code_289',
                        //'code_039',
                        //'code_578',
                        //'code_678',
                        //'code_023',
                        //'code_158',
                        //'code_017',
                        //'code_046',
                        //'code_038',
                        //'code_129',
                        //'code_024',
                        //'code_247',
                        //'code_456',
                        //'code_136',
                        //'code_568',
                        //'code_169',
                        //'code_026',
                        //'code_027',
                        //'code_058',
                        //'code_269',
                        //'code_089',
                        //'code_149',
                        //'code_259',
                        //'code_689',
                        //'code_367',
                        //'code_128',
                        //'code_127',
                        //'code_135',
                        //'code_028',
                        //'code_357',
                        //'code_146',
                        //'code_048',
                        //'code_059',
                        //'code_147',
                        //'code_168',
                        //'code_234',
                        //'code_467',
                        //'code_358',
                        //'code_189',
                        //'code_268',
                        //'code_468',
                        //'code_679',
                        //'code_045',
                        //'code_179',
                        //'code_245',
                        //'code_279',
                        //'code_235',
                        //'code_257',
                        //'code_079',
                        //'code_489',
                        //'code_047',
                        //'code_359',
                        //'code_124',
                        //'code_068',
                        //'code_239',
                        //'code_035',
                        //'code_246',
                        //'code_458',
                        //'code_479',
                        //'code_057',
                        //'code_579',
                        //'code_016',
                        //'code_157',
                        //'code_457',
                        //'code_237',
                        //'code_249',
                        //'code_389',
                        //'code_159',
                        //'code_049',
                        //'code_369',
                        //'code_379',
                        //'code_349',
                        //'code_346',
                        //'code_345',
                        //'code_368',
                        //'code_459',
                        //'code_899',
                        //'code_499',
                        //'code_099',
                        //'code_448',
                        //'code_114',
                        //'code_122',
                        //'code_399',
                        //'code_116',
                        //'code_334',
                        //'code_299',
                        //'code_044',
                        //'code_889',
                        //'code_001',
                        //'code_668',
                        //'code_166',
                        //'code_007',
                        //'code_778',
                        //'code_003',
                        //'code_244',
                        //'code_004',
                        //'code_229',
                        //'code_288',
                        //'code_477',
                        //'code_337',
                        //'code_119',
                        //'code_225',
                        //'code_447',
                        //'code_355',
                        //'code_377',
                        //'code_688',
                        //'code_022',
                        //'code_266',
                        //'code_799',
                        //'code_228',
                        //'code_115',
                        //'code_779',
                        //'code_188',
                        //'code_199',
                        //'code_223',
                        //'code_366',
                        //'code_002',
                        //'code_055',
                        //'code_336',
                        //'code_445',
                        //'code_033',
                        //'code_117',
                        //'code_227',
                        //'code_557',
                        //'code_118',
                        //'code_339',
                        //'code_344',
                        //'code_446',
                        //'code_113',
                        //'code_005',
                        //'code_224',
                        //'code_255',
                        //'code_699',
                        //'code_006',
                        //'code_011',
                        //'code_088',
                        //'code_277',
                        //'code_388',
                        //'code_788',
                        //'code_449',
                        //'code_466',
                        //'code_133',
                        //'code_556',
                        //'code_112',
                        //'code_488',
                        //'code_455',
                        //'code_667',
                        //'code_335',
                        //'code_233',
                        //'code_577',
                        //'code_009',
                        //'code_559',
                        //'code_008',
                        //'code_077',
                        //'code_599',
                        //'code_066',
                        //'code_338',
                        //'code_588',
                        //'code_669',
                        //'code_677',
                        //'code_177',
                        //'code_566',
                        //'code_226',
                        //'code_144',
                        //'code_558',
                        //'code_155',
                        //'code_000',
                        //'code_222',
                        //'code_444',
                        //'code_999',
                        //'code_555',
                        //'code_777',
                        //'code_666',
                        //'code_888',
                        //'code_333',
                        //'code_111',
                        //'lottery_type',
                        //'created_at',
                        //'updated_at',
                        //'update_time',

                        //['class' => 'yii\grid\ActionColumn'],
                    ],
                ]); ?>
            <?php //Pjax::end(); ?>
            </div>
        </div>
    </section>
    <!-- page end-->
</section>
