[unix_http_server]
file=/www/server/supervisor/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/www/server/supervisor/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/www/server/supervisor/run/supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200
childlogdir=/www/server/supervisor/logs

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///www/server/supervisor/run/supervisor.sock

[include]
files=/www/server/supervisor/conf.d/*.ini
