# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grabLtDatas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 320)
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #f5f5f5;
            }
            QPushButton {
                border: none;
                border-radius: 8px;
                padding: 12px 30px;
                font-size: 14px;
                font-weight: bold;
            }
            QPushButton#startBtn {
                background-color: #4CAF50;
                color: white;
            }
            QPushButton#startBtn:hover {
                background-color: #45a049;
            }
            QPushButton#startBtn:pressed {
                background-color: #3d8b40;
            }
            QPushButton#pauseBtn {
                background-color: #f44336;
                color: white;
            }
            QPushButton#pauseBtn:hover {
                background-color: #d32f2f;
            }
            QPushButton#pauseBtn:pressed {
                background-color: #b71c1c;
            }
            QPushButton#pushSwitchBtn {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 8px 15px;
                font-size: 12px;
                font-weight: bold;
            }
            QPushButton#pushSwitchBtn:hover {
                background-color: #45a049;
            }
            QPushButton#pushSwitchBtn:pressed {
                background-color: #3d8b40;
            }
            QPushButton#pushSwitchBtnOff {
                background-color: #9e9e9e;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 8px 15px;
                font-size: 12px;
                font-weight: bold;
            }
            QPushButton#pushSwitchBtnOff:hover {
                background-color: #757575;
            }
            QPushButton#pushSwitchBtnOff:pressed {
                background-color: #616161;
            }
            QLabel {
                font-size: 13px;
                color: #333;
            }
            QLabel#titleLabel {
                font-size: 16px;
                font-weight: bold;
                color: #2196F3;
            }
            QLabel#dataLabel {
                font-size: 18px;
                font-weight: bold;
                color: #f44336;
                background-color: white;
                border-radius: 6px;
                padding: 10px;
                border: 2px solid #e0e0e0;
            }
        """)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 标题
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(20, 20, 460, 30))
        self.titleLabel.setObjectName("titleLabel")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        
        # 开奖数据显示区域
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataLabel.setGeometry(QtCore.QRect(20, 60, 460, 120))
        self.dataLabel.setObjectName("dataLabel")
        self.dataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataLabel.setWordWrap(True)
        
        # 控制按钮（只有一个，会切换状态）- 居中
        window_width = 500
        button_width = 200
        button_x = (window_width - button_width) // 2  # 居中计算
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(button_x, 190, button_width, 50))
        self.startBtn.setObjectName("startBtn")
        
        # 推送开关按钮（右侧，调小尺寸）
        push_button_width = 110
        push_button_x = window_width - push_button_width - 20  # 靠右，距离右边20像素
        self.pushSwitchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pushSwitchBtn.setGeometry(QtCore.QRect(push_button_x, 190, push_button_width, 40))
        self.pushSwitchBtn.setObjectName("pushSwitchBtn")
        
        # 隐藏关闭按钮（不再使用）
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setVisible(False)
        self.closeBtn.setObjectName("closeBtn")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "开奖数据采集"))
        self.titleLabel.setText(_translate("MainWindow", "幸运五星彩 - 开奖数据采集"))
        self.dataLabel.setText(_translate("MainWindow", "等待开启采集..."))
        self.pushSwitchBtn.setText(_translate("MainWindow", "推送：已开启"))
        self.startBtn.setText(_translate("MainWindow", "开启"))
        self.closeBtn.setText(_translate("MainWindow", "关闭"))
