# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LuckyClientOppSite.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)  # 增加默认窗口大小
        
        # 修改窗口样式表，确保整体背景不透明
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #f5f6fa;
            }
            
            QWidget#centralwidget {
                background-color: #f5f6fa;
                border: 1px solid #dcdde1;
                border-radius: 10px;
            }
            
            QGroupBox {
                background-color: white;
                border: 1px solid #dcdde1;
                border-radius: 8px;
                margin-top: 1ex;
                font-size: 14px;
                color: #2f3542;
                padding: 10px;
            }
            
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 5px;
                background-color: white;
                color: #2f3542;
            }
            
            QLineEdit {
                border: 1px solid #dcdde1;
                border-radius: 4px;
                padding: 5px 8px;
                background-color: white;
                min-width: 200px;
                max-width: 800px;  /* 增加最大宽度 */
                height: 30px;
                font-size: 13px;
                color: #2f3542;
            }
            
            QLineEdit:focus {
                border: 2px solid #4a69bd;
            }
            
            QPushButton {
                background-color: #4a69bd;
                color: white;
                border-radius: 4px;
                padding: 5px 15px;
                height: 32px;
                font-size: 13px;
                border: none;
            }
            
            QPushButton:hover {
                background-color: #6a89cc;
            }
            
            QPushButton:pressed {
                background-color: #3867b9;
            }
            
            QLabel {
                color: #2f3542;
                font-size: 13px;
                font-weight: normal;
                background: transparent;
            }
            
            QTableWidget {
                background-color: white;
                border: 1px solid #dcdde1;
                border-radius: 6px;
                gridline-color: #f1f2f6;
                padding: 5px;
            }
            
            QTableWidget::item {
                padding: 8px;
                border-bottom: 1px solid #f1f2f6;
                color: #2f3542;
            }
            
            QHeaderView::section {
                background-color: #f5f6fa;
                padding: 8px;
                border: none;
                font-weight: bold;
                color: #2f3542;
            }
            
            QPlainTextEdit {
                background-color: white;
                border: 1px solid #dcdde1;
                border-radius: 6px;
                padding: 5px;
                color: #2f3542;
            }
            
            QMenuBar {
                background-color: #f5f6fa;
                color: #2f3542;
            }
            
            QStatusBar {
                background-color: #f5f6fa;
                color: #2f3542;
            }
            
            /* 滚动条样式 */
            QScrollBar:vertical {
                border: none;
                background-color: #f5f6fa;
                width: 10px;
                margin: 0px;
            }
            
            QScrollBar::handle:vertical {
                background-color: #dcdde1;
                min-height: 30px;
                border-radius: 5px;
            }
            
            QScrollBar::handle:vertical:hover {
                background-color: #a4b0be;
            }
        """)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_6.setSpacing(15)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.UserInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.UserInfo.setObjectName("UserInfo")
        self.UserInfo.setContentsMargins(20, 20, 20, 20)


        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.UserInfo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_label.sizePolicy().hasHeightForWidth())
        self.username_label.setSizePolicy(sizePolicy)
        self.username_label.setStyleSheet("")
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.username_val = QtWidgets.QLineEdit(self.UserInfo)
        self.username_val.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_val.sizePolicy().hasHeightForWidth())
        self.username_val.setSizePolicy(sizePolicy)
        self.username_val.setMaxLength(50)
        self.username_val.setObjectName("username_val")
        self.username_val.setMaximumWidth(100)
        self.horizontalLayout.addWidget(self.username_val)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pwd_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwd_label.sizePolicy().hasHeightForWidth())
        self.pwd_label.setSizePolicy(sizePolicy)
        self.pwd_label.setObjectName("pwd_label")
        self.horizontalLayout_2.addWidget(self.pwd_label)
        self.pwd_val = QtWidgets.QLineEdit(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwd_val.sizePolicy().hasHeightForWidth())
        self.pwd_val.setSizePolicy(sizePolicy)
        self.pwd_val.setObjectName("pwd_val")
        self.pwd_val.setMaximumWidth(100)
        self.horizontalLayout_2.addWidget(self.pwd_val)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.domain_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain_label.sizePolicy().hasHeightForWidth())
        self.domain_label.setSizePolicy(sizePolicy)
        self.domain_label.setObjectName("domain_label")
        self.horizontalLayout_3.addWidget(self.domain_label)
        self.domain_val = QtWidgets.QLineEdit(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain_val.sizePolicy().hasHeightForWidth())
        self.domain_val.setSizePolicy(sizePolicy)
        self.domain_val.setObjectName("domain_val")
        self.domain_val.setMinimumWidth(120)  # 域名输入框自适应宽度
        self.horizontalLayout_3.addWidget(self.domain_val)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.balance_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balance_label.sizePolicy().hasHeightForWidth())
        self.balance_label.setSizePolicy(sizePolicy)
        self.balance_label.setObjectName("balance_label")
        self.horizontalLayout_11.addWidget(self.balance_label)
        self.balance = QtWidgets.QLineEdit(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balance.sizePolicy().hasHeightForWidth())
        self.balance.setSizePolicy(sizePolicy)
        self.balance.setObjectName("balance")
        self.balance.setMaximumWidth(100)
        self.horizontalLayout_11.addWidget(self.balance)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.token_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.token_label.sizePolicy().hasHeightForWidth())
        self.token_label.setSizePolicy(sizePolicy)
        self.token_label.setObjectName("token_label")
        self.horizontalLayout_5.addWidget(self.token_label)
        self.token_val = QtWidgets.QLineEdit(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.token_val.sizePolicy().hasHeightForWidth())
        self.token_val.setSizePolicy(sizePolicy)
        self.token_val.setObjectName("token_val")
        self.token_val.setMaximumWidth(100)
        self.horizontalLayout_5.addWidget(self.token_val)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        
        # 添加过期时间控件
        self.horizontalLayout_expire = QtWidgets.QHBoxLayout()
        self.horizontalLayout_expire.setObjectName("horizontalLayout_expire")
        self.expire_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expire_label.sizePolicy().hasHeightForWidth())
        self.expire_label.setSizePolicy(sizePolicy)
        self.expire_label.setObjectName("expire_label")
        self.horizontalLayout_expire.addWidget(self.expire_label)
        self.expire_val = QtWidgets.QLineEdit(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expire_val.sizePolicy().hasHeightForWidth())
        self.expire_val.setSizePolicy(sizePolicy)
        self.expire_val.setObjectName("expire_val")
        self.expire_val.setMaximumWidth(100)
        self.expire_val.setReadOnly(True)
        self.horizontalLayout_expire.addWidget(self.expire_val)
        self.horizontalLayout_expire.setStretch(0, 2)
        self.horizontalLayout_expire.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_expire)
        
        # 添加浏览器选择控件
        self.horizontalLayout_browser = QtWidgets.QHBoxLayout()
        self.horizontalLayout_browser.setObjectName("horizontalLayout_browser")
        self.browser_label = QtWidgets.QLabel(self.UserInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browser_label.sizePolicy().hasHeightForWidth())
        self.browser_label.setSizePolicy(sizePolicy)
        self.browser_label.setObjectName("browser_label")
        self.horizontalLayout_browser.addWidget(self.browser_label)
        self.browser_group = QtWidgets.QButtonGroup(self.UserInfo)
        self.browser_group.setObjectName("browser_group")
        self.chrome_radio = QtWidgets.QRadioButton(self.UserInfo)
        self.chrome_radio.setObjectName("chrome_radio")
        self.browser_group.addButton(self.chrome_radio)
        self.horizontalLayout_browser.addWidget(self.chrome_radio)
        self.firefox_radio = QtWidgets.QRadioButton(self.UserInfo)
        self.firefox_radio.setObjectName("firefox_radio")
        self.browser_group.addButton(self.firefox_radio)
        self.horizontalLayout_browser.addWidget(self.firefox_radio)
        self.open_browser_checkbox = QtWidgets.QCheckBox(self.UserInfo)
        self.open_browser_checkbox.setObjectName("open_browser_checkbox")
        self.open_browser_checkbox.setToolTip("仅在盘口会话失效、需要重新登录时启用")
        self.horizontalLayout_browser.addWidget(self.open_browser_checkbox)
        self.horizontalLayout_browser.setStretch(0, 2)
        self.horizontalLayout_browser.setStretch(1, 2)
        self.horizontalLayout_browser.setStretch(2, 2)
        self.horizontalLayout_browser.setStretch(3, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_browser)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_play_btn = QtWidgets.QPushButton(self.UserInfo)
        self.start_play_btn.setObjectName("start_play_btn")
        self.horizontalLayout_4.addWidget(self.start_play_btn)
        self.sync_balance_btn = QtWidgets.QPushButton(self.UserInfo)
        self.sync_balance_btn.setObjectName("sync_balance_btn")
        self.horizontalLayout_4.addWidget(self.sync_balance_btn)
        self.UserLoginBtn = QtWidgets.QPushButton(self.UserInfo)
        self.UserLoginBtn.setObjectName("UserLoginBtn")
        self.horizontalLayout_4.addWidget(self.UserLoginBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.UserInfo)
        self.ProxyInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.ProxyInfo.setObjectName("ProxyInfo")
        self.ProxyInfo.setContentsMargins(20, 20, 20, 20)


        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ProxyInfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.agent_username_label = QtWidgets.QLabel(self.ProxyInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_username_label.sizePolicy().hasHeightForWidth())
        self.agent_username_label.setSizePolicy(sizePolicy)
        self.agent_username_label.setStyleSheet("")
        self.agent_username_label.setObjectName("agent_username_label")
        self.horizontalLayout_7.addWidget(self.agent_username_label)
        self.agent_username_val = QtWidgets.QLineEdit(self.ProxyInfo)
        self.agent_username_val.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_username_val.sizePolicy().hasHeightForWidth())
        self.agent_username_val.setSizePolicy(sizePolicy)
        self.agent_username_val.setMaxLength(50)
        self.agent_username_val.setObjectName("agent_username_val")
        self.agent_username_val.setMaximumWidth(100)
        self.horizontalLayout_7.addWidget(self.agent_username_val)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.agent_password_label = QtWidgets.QLabel(self.ProxyInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_password_label.sizePolicy().hasHeightForWidth())
        self.agent_password_label.setSizePolicy(sizePolicy)
        self.agent_password_label.setObjectName("agent_password_label")
        self.horizontalLayout_8.addWidget(self.agent_password_label)
        self.agent_password_val = QtWidgets.QLineEdit(self.ProxyInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_password_val.sizePolicy().hasHeightForWidth())
        self.agent_password_val.setSizePolicy(sizePolicy)
        self.agent_password_val.setObjectName("agent_password_val")
        self.agent_password_val.setMaximumWidth(100)
        self.horizontalLayout_8.addWidget(self.agent_password_val)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.agent_domain_label = QtWidgets.QLabel(self.ProxyInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_domain_label.sizePolicy().hasHeightForWidth())
        self.agent_domain_label.setSizePolicy(sizePolicy)
        self.agent_domain_label.setObjectName("agent_domain_label")
        self.horizontalLayout_9.addWidget(self.agent_domain_label)
        self.agent_domain_val = QtWidgets.QLineEdit(self.ProxyInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_domain_val.sizePolicy().hasHeightForWidth())
        self.agent_domain_val.setSizePolicy(sizePolicy)
        self.agent_domain_val.setObjectName("agent_domain_val")
        self.agent_domain_val.setMinimumWidth(120)
        self.horizontalLayout_9.addWidget(self.agent_domain_val)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.start_play_btn_2 = QtWidgets.QPushButton(self.ProxyInfo)
        self.start_play_btn_2.setObjectName("start_play_btn_2")
        self.horizontalLayout_10.addWidget(self.start_play_btn_2)
        self.AgentLoginBtn = QtWidgets.QPushButton(self.ProxyInfo)
        self.AgentLoginBtn.setObjectName("AgentLoginBtn")
        self.horizontalLayout_10.addWidget(self.AgentLoginBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.ProxyInfo)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        self.mainRight = QtWidgets.QVBoxLayout()
        self.mainRight.setObjectName("mainRight")
        self.mainRight_top = QtWidgets.QHBoxLayout()
        self.mainRight_top.setObjectName("mainRight_top")
        self.tip_msg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tip_msg.setObjectName("tip_msg")
        self.mainRight_top.addWidget(self.tip_msg)
        self.search_lists = QtWidgets.QPushButton(self.centralwidget)
        self.search_lists.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lists.sizePolicy().hasHeightForWidth())
        self.search_lists.setSizePolicy(sizePolicy)
        self.search_lists.setMaximumSize(QtCore.QSize(50, 70))
        self.search_lists.setObjectName("search_lists")
        self.mainRight_top.addWidget(self.search_lists)
        self.mainRight.addLayout(self.mainRight_top)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMaximumSize(QtCore.QSize(2540, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Interactive)
        self.tableWidget.setColumnWidth(0, 100)  # 期号
        self.tableWidget.setColumnWidth(1, 150)  # 投注号码
        self.tableWidget.setColumnWidth(6, 150)  # 号码
        self.tableWidget.setColumnWidth(9, 180)  # 时间
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.mainRight.addWidget(self.tableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.mainRight.addLayout(self.horizontalLayout_6)
        self.mainRight.setStretch(0, 2)
        self.mainRight.setStretch(1, 17)
        self.mainRight.setStretch(2, 1)
        self.horizontalLayout_12.addLayout(self.mainRight)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setMinimumSize(1200, 900)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Add new query group box
        self.QueryGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.QueryGroup.setObjectName("QueryGroup")
        self.QueryGroup.setTitle("代理查询")
        self.QueryGroup.setContentsMargins(20, 20, 20, 20)


        # Create vertical layout for the query group
        self.queryLayout = QtWidgets.QVBoxLayout(self.QueryGroup)

        # Create horizontal layout for period and category
        self.queryHLayout = QtWidgets.QHBoxLayout()

        # Add period number label and field
        self.period_label = QtWidgets.QLabel("期号:")
        self.period_val = QtWidgets.QLineEdit()
        #self.period_val.setEnabled(False)  # Make it read-only

        # Add category combobox
        self.category_label = QtWidgets.QLabel("类型:")
        self.category_combo = QtWidgets.QComboBox()
        self.category_combo.addItems([
            "全部", "一定位", "口XXXX", "X口XXX", "XX口XX", "XXX口X", "XXXX口",
            "二定位", "口口XX", "口X口X", "口XX口", "X口X口", "X口口X", "XX口口",
            "五位二定", "口XXX口", "X口XX口", "XX口X口", "XXX口口", "三定位",
            "口口口X", "口口X口", "口X口口", "X口口口", "四定位", "二字现",
            "三字现", "四字现", "快打", "快选", "快译", "txt导入", "一定", "二定"
        ])

        # Add query button
        self.query_btn = QtWidgets.QPushButton("查询")
        self.query_btn.clicked.connect(self.query_bet_details)

        # Add result text area
        self.query_result = QtWidgets.QPlainTextEdit()
        #self.query_result.setReadOnly(True)

        # Add widgets to layouts
        self.queryHLayout.addWidget(self.period_label)
        self.queryHLayout.addWidget(self.period_val)
        self.queryHLayout.addWidget(self.category_label)
        self.queryHLayout.addWidget(self.category_combo)
        self.queryHLayout.addWidget(self.query_btn)

        self.queryLayout.addLayout(self.queryHLayout)
        self.queryLayout.addWidget(self.query_result)

        # Add QueryGroup to main layout
        self.verticalLayout_5.addWidget(self.QueryGroup)

        # 设置字体和样式
        self.setupFontsAndStyles()
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setupFontsAndStyles(self):
        """设置字体和样式"""
        # 设置标签字体
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        
        # 用户信息框标签
        self.username_label.setFont(font)
        self.pwd_label.setFont(font)
        self.domain_label.setFont(font)
        self.balance_label.setFont(font)
        self.token_label.setFont(font)
        
        # 代理信息框标签
        self.agent_username_label.setFont(font)
        self.agent_password_label.setFont(font)
        self.agent_domain_label.setFont(font)
        
        # 代理查询框标签
        self.period_label.setFont(font)
        self.category_label.setFont(font)
        
        # 设置输入框字体
        input_font = QtGui.QFont()
        input_font.setPointSize(9)
        
        # 用户信息框输入框
        self.username_val.setFont(input_font)
        self.pwd_val.setFont(input_font)
        self.domain_val.setFont(input_font)
        self.balance.setFont(input_font)
        self.token_val.setFont(input_font)
        
        # 代理信息框输入框
        self.agent_username_val.setFont(input_font)
        self.agent_password_val.setFont(input_font)
        self.agent_domain_val.setFont(input_font)
        
        # 代理查询框输入框
        self.period_val.setFont(input_font)
        self.category_combo.setFont(input_font)
        
        # 设置按钮字体
        button_font = QtGui.QFont()
        button_font.setPointSize(9)
        button_font.setBold(True)
        
        # 设置所有按钮字体
        for button in [self.start_play_btn, self.sync_balance_btn, self.UserLoginBtn,
                      self.start_play_btn_2, self.AgentLoginBtn, self.query_btn,
                      self.search_lists, self.pushButton_2]:
            if hasattr(self, button.objectName()):
                button.setFont(button_font)
        
        # 设置GroupBox标题字体
        title_font = QtGui.QFont()
        title_font.setPointSize(11)
        title_font.setBold(True)
        
        self.UserInfo.setFont(title_font)
        self.ProxyInfo.setFont(title_font)
        self.QueryGroup.setFont(title_font)
        
        # 设置GroupBox最小高度，确保用户信息框和代理信息框高度一致
        self.UserInfo.setMinimumHeight(280)
        self.ProxyInfo.setMinimumHeight(200)
        self.QueryGroup.setMinimumHeight(120)
        
        # 设置垂直布局间距，增加用户信息框内部行间距
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_5.setSpacing(15)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UserInfo.setTitle(_translate("MainWindow", "用户信息"))
        self.username_label.setText(_translate("MainWindow", "账号"))
        self.pwd_label.setText(_translate("MainWindow", "密码"))
        self.domain_label.setText(_translate("MainWindow", "域名"))
        self.balance_label.setText(_translate("MainWindow", "积分"))
        self.token_label.setText(_translate("MainWindow", "TOKEN"))
        self.expire_label.setText(_translate("MainWindow", "过期时间"))
        self.browser_label.setText(_translate("MainWindow", "浏览器"))
        self.chrome_radio.setText(_translate("MainWindow", "Chrome"))
        self.firefox_radio.setText(_translate("MainWindow", "Firefox"))
        self.open_browser_checkbox.setText(_translate("MainWindow", "打开浏览器登录"))
        self.start_play_btn.setText(_translate("MainWindow", "开始游戏"))
        self.sync_balance_btn.setText(_translate("MainWindow", "重登"))
        self.UserLoginBtn.setText(_translate("MainWindow", "登录"))
        self.ProxyInfo.setTitle(_translate("MainWindow", "代理信息"))
        self.agent_username_label.setText(_translate("MainWindow", "账号"))
        self.agent_password_label.setText(_translate("MainWindow", "密码"))
        self.agent_domain_label.setText(_translate("MainWindow", "域名"))
        self.start_play_btn_2.setText(_translate("MainWindow", "开始游戏"))
        self.AgentLoginBtn.setText(_translate("MainWindow", "登录"))
        self.search_lists.setText(_translate("MainWindow", "搜索"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "投注号码"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "投注"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "中奖"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "倍数"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "利润"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "号码"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "操作"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "方式"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "时间"))
        self.pushButton_2.setText(_translate("MainWindow", "查询"))
