[system_configs]
lottery_type = 8
is_test = 0
robot_domain = http://18.163.69.56:8090
lt_type = lucky5
official_site = https://web01.cc138001.com
runtime_mode = background
driver_name = chrome
binary_location = auto
binary_location_mac = auto
chromedriver_path = auto
geckodriver_path = auto
preferred_browser = chrome
daily_restart_hour = 7
daily_restart_minute = 45
