CREATE TABLE `lt_bet_error_plans_task` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `codes` longtext COMMENT '投注号码',
  `uid` int(11) DEFAULT NULL COMMENT '用户id',
  `agent_id` int(11) DEFAULT NULL COMMENT '代理id',
  `account` varchar(24) DEFAULT NULL,
  `bet_url` varchar(240) DEFAULT NULL,
  `bet_headers` longtext DEFAULT NULL,
  `post_datas` longtext COMMENT '请求数据',
  `playway` tinyint(3) DEFAULT '10' COMMENT '投注方式：1二定2三定3四定',
  `tz_type` tinyint(3) DEFAULT '0' COMMENT '投注类型',
  `playway_name` varchar(32) DEFAULT NULL COMMENT '投注方式',
  `bet_money` decimal(11,2) DEFAULT '0.00' COMMENT '投注金额',
  `single` float DEFAULT NULL COMMENT '倍数(元)',
  `qihao` varchar(20) DEFAULT NULL COMMENT '期号',
  `kj_codes` varchar(24) DEFAULT NULL COMMENT '开奖号码',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态：0:正常1:处理成功2:处理失败',
  `sn` varchar(255) DEFAULT NULL COMMENT '方案号',
  `snid` varchar(240) COMMENT '订单号，用于撤单',
  `plan_id` int(11) DEFAULT NULL COMMENT '计划id',
  `tz_system_id` int(11) DEFAULT NULL COMMENT '投注系统tz_systems.id',
  `lotteryclass` varchar(10) DEFAULT 'ssc' COMMENT '彩种',
  `lottery_type` tinyint(1) DEFAULT '5' COMMENT '彩种类型',
  `post_desc` varchar(240) COMMENT '下注文本',
  `error_desc` longtext COMMENT '错误描述',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_at` int(11) DEFAULT NULL COMMENT '更新时间',
  `created_at` int(11) DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `account` (`account`) USING BTREE,
  KEY `qihao` (`qihao`),
  KEY `bet_money` (`bet_money`),
  KEY `playway` (`playway`),
  KEY `uid` (`uid`),
  KEY `uid_lottery_type` (`uid`,`lottery_type`),
  KEY `account_lottery_type` (`account`,`lottery_type`),
  KEY `status_lottery_type` (`status`,`lottery_type`),
  KEY `plan_id` (`plan_id`),
  KEY `lottery_type` (`lottery_type`),
  FULLTEXT KEY `codes` (`codes`),
  FULLTEXT KEY `snid` (`snid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投注失败记录重推任务表';